import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Sparkles, BookOpen, Brain, Timer, CalendarCheck, BarChart3, ArrowRight, GraduationCap, MessageSquare, Layers } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "StudentHub AI — Your AI-powered study workspace" },
      { name: "description", content: "All-in-one study platform: assignments, notes, AI tutor, flashcards, focus timer, and goals — built for students." },
      { property: "og:title", content: "StudentHub AI" },
      { property: "og:description", content: "The premium AI-powered workspace for students." },
    ],
  }),
  component: Index,
});

const FEATURES = [
  { icon: BookOpen, title: "Smart assignments", desc: "Track every task with priority, subjects, and due-date reminders." },
  { icon: MessageSquare, title: "AI study assistant", desc: "Explain concepts, summarize notes, draft revision plans — instantly." },
  { icon: Layers, title: "Flashcards & notes", desc: "Rich notes with tags, plus spaced-repetition decks generated by AI." },
  { icon: Timer, title: "Focus timer", desc: "Pomodoro sessions that automatically log to your study history." },
  { icon: CalendarCheck, title: "Weekly timetable", desc: "Color-coded schedule with class reminders and quick edits." },
  { icon: BarChart3, title: "Productivity analytics", desc: "Track streaks, study hours, and subject-level performance." },
];

function Index() {
  return (
    <div className="min-h-screen bg-background text-foreground overflow-hidden relative">
      {/* Ambient glow */}
      <div className="pointer-events-none absolute -top-40 left-1/2 -translate-x-1/2 size-[900px] rounded-full opacity-30 blur-[140px] gradient-brand" />
      <div className="pointer-events-none absolute top-1/2 -right-40 size-[500px] rounded-full opacity-20 blur-[120px] bg-[oklch(0.7_0.2_320)]" />

      <header className="relative z-10 flex items-center justify-between px-6 md:px-10 py-6">
        <Link to="/" className="flex items-center gap-2.5">
          <div className="size-9 rounded-xl gradient-brand grid place-items-center font-bold text-white shadow-[var(--shadow-glow)]">
            <GraduationCap className="size-5" />
          </div>
          <span className="text-lg font-bold tracking-tight">StudentHub <span className="gradient-text">AI</span></span>
        </Link>
        <div className="flex items-center gap-2">
          <Link to="/auth"><Button variant="ghost" size="sm">Sign in</Button></Link>
          <Link to="/auth"><Button size="sm" className="gradient-brand text-white border-0 shadow-[var(--shadow-glow)]">Get started</Button></Link>
        </div>
      </header>

      <main className="relative z-10">
        <section className="px-6 md:px-10 pt-16 md:pt-24 pb-20 max-w-6xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-card text-xs font-medium text-muted-foreground mb-6 animate-fade-in-up">
            <Sparkles className="size-3 text-brand" />
            Built for high school & college students
          </div>
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight text-balance mb-6 animate-fade-in-up [animation-delay:80ms]">
            Your AI-powered <span className="gradient-text">study workspace</span>
          </h1>
          <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed mb-10 animate-fade-in-up [animation-delay:160ms]">
            Assignments, notes, flashcards, timetable, and an AI tutor — all in one premium workspace designed to help you focus, study smarter, and stay on top of every deadline.
          </p>
          <div className="flex items-center justify-center gap-3 animate-fade-in-up [animation-delay:240ms]">
            <Link to="/auth">
              <Button size="lg" className="gradient-brand text-white border-0 shadow-[var(--shadow-glow)] h-12 px-6">
                Start studying free <ArrowRight className="size-4 ml-1" />
              </Button>
            </Link>
            <Link to="/auth"><Button size="lg" variant="outline" className="h-12 px-6 glass-card">Sign in</Button></Link>
          </div>
        </section>

        <section className="px-6 md:px-10 max-w-6xl mx-auto pb-24">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
            {FEATURES.map((f, i) => (
              <div key={f.title} className="glass-card rounded-2xl p-6 hover:border-brand/40 transition-all animate-fade-in-up" style={{ animationDelay: `${i * 60}ms` }}>
                <div className="size-11 rounded-xl bg-brand/10 border border-brand/20 grid place-items-center text-brand mb-4">
                  <f.icon className="size-5" />
                </div>
                <h3 className="font-semibold mb-1.5">{f.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="px-6 md:px-10 max-w-4xl mx-auto pb-24 text-center">
          <div className="glass-card rounded-3xl p-10 md:p-14 relative overflow-hidden">
            <div className="pointer-events-none absolute -top-20 -right-20 size-60 rounded-full gradient-brand opacity-20 blur-3xl" />
            <Brain className="size-10 mx-auto mb-4 text-brand" />
            <h2 className="text-2xl md:text-3xl font-bold mb-3">Ready to study smarter?</h2>
            <p className="text-muted-foreground mb-6">Join thousands of students already using StudentHub AI. Free to start, no credit card required.</p>
            <Link to="/auth">
              <Button size="lg" className="gradient-brand text-white border-0 shadow-[var(--shadow-glow)] h-12 px-8">
                Create your account <ArrowRight className="size-4 ml-1" />
              </Button>
            </Link>
          </div>
        </section>

        <footer className="px-6 md:px-10 py-8 text-center text-xs text-muted-foreground border-t border-border">
          © {new Date().getFullYear()} StudentHub AI. Built for students, by students.
        </footer>
      </main>
    </div>
  );
}
