/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTimerRouteImport } from './routes/_authenticated/timer'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPastPapersRouteImport } from './routes/_authenticated/past-papers'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPastPapersRoute = AuthenticatedPastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/past-papers': typeof AuthenticatedPastPapersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/timetable': typeof AuthenticatedTimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/past-papers': typeof AuthenticatedPastPapersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/timetable': typeof AuthenticatedTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/past-papers': typeof AuthenticatedPastPapersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timer': typeof AuthenticatedTimerRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/analytics'
    | '/assignments'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flashcards'
    | '/goals'
    | '/notes'
    | '/past-papers'
    | '/settings'
    | '/timer'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/analytics'
    | '/assignments'
    | '/calendar'
    | '/dashboard'
    | '/files'
    | '/flashcards'
    | '/goals'
    | '/notes'
    | '/past-papers'
    | '/settings'
    | '/timer'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/analytics'
    | '/_authenticated/assignments'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/files'
    | '/_authenticated/flashcards'
    | '/_authenticated/goals'
    | '/_authenticated/notes'
    | '/_authenticated/past-papers'
    | '/_authenticated/settings'
    | '/_authenticated/timer'
    | '/_authenticated/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timer': {
      id: '/_authenticated/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/past-papers': {
      id: '/_authenticated/past-papers'
      path: '/past-papers'
      fullPath: '/past-papers'
      preLoaderRoute: typeof AuthenticatedPastPapersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPastPapersRoute: typeof AuthenticatedPastPapersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPastPapersRoute: AuthenticatedPastPapersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
